version: "3.4"

services:
  ontop:
    build:
      context: ./
      dockerfile: infrastructure/docker/ontop/Dockerfile
      target: dev
    env_file: .env
    restart: unless-stopped
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/odh.ttl
      ONTOP_MAPPING_FILE: /opt/ontop/input/odh.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/odh.docker.properties
      ONTOP_PORTAL_FILE: /opt/ontop/input/odh.portal.toml
      ONTOP_PREDEFINED_CONFIG: /opt/ontop/input/predefined/predefined.json
      ONTOP_PREDEFINED_QUERIES: /opt/ontop/input/predefined/queries.toml
      ONTOP_CONTEXTS: /opt/ontop/input/predefined/contexts.json
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      ONTOP_DEV_MODE: "true"
      EXTRA_FLYWAY_OPTIONS: "-mixed=true"
    volumes:
      - ./vkg:/opt/ontop/input
      - ./jdbc:/opt/ontop/jdbc
      - ./src:/opt/ontop/src
    entrypoint: ["/wait-for-it.sh","master-db:5432","--timeout=0","--strict", "--", "/entrypoint.sh"]
  gatekeeper:
    build:
      context: ./
      dockerfile: infrastructure/docker/gatekeeper/Dockerfile
    environment:
      PROXY_DISCOVERY_URL: "${KEYCLOAK_ENDPOINT}"
      PROXY_REDIRECTION_URL: "http://localhost:${SERVER_PORT}"
      PROXY_CLIENT_ID: "${KEYCLOAK_CLIENT_ID}"
      PROXY_CLIENT_SECRET: "${KEYCLOAK_CLIENT_SECRET}"
      PROXY_ENCRYPTION_KEY: "${KEYCLOAK_ENCRYPTION_KEY}"
  nginx:
    build:
      context: ./
      dockerfile: infrastructure/docker/nginx/Dockerfile
    env_file: .env
    ports:
      - "${SERVER_PORT}:80"
  master-db:
    image: ontopicvkg/odh-tourism-db:master
    environment:
      - POSTGRES_USER=tourismuser
      - POSTGRES_PASSWORD=postgres2
    ports:
      - "${DEV_MASTER_POSTGRES_PORT}:5432"
  slave-db:
    image: postgres:12.1
    shm_size: 1g
    ports:
      - "${MAPPED_POSTGRES_PORT}:5432"
    command: ["postgres", "-c", "wal_level=logical"]
    environment:
      - POSTGRES_USER=tourismuser
      - POSTGRES_PASSWORD=postgres2
