version: "3.4"

services:
  ontop:
    image: ${DOCKER_IMAGE_ONTOP}:${DOCKER_TAG}
    restart: unless-stopped
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/odh.ttl
      ONTOP_MAPPING_FILE: /opt/ontop/input/odh.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/odh.docker.properties
      ONTOP_PORTAL_FILE: /opt/ontop/input/odh.portal.toml
      ONTOP_PREDEFINED_CONFIG: /opt/ontop/input/predefined/predefined.json
      ONTOP_PREDEFINED_QUERIES: /opt/ontop/input/predefined/queries.toml
      ONTOP_CONTEXTS: /opt/ontop/input/predefined/contexts.json
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      COPY_POSTGRES_HOST: "${COPY_POSTGRES_HOST}"
      COPY_POSTGRES_DB: "${COPY_POSTGRES_DB}"
      COPY_POSTGRES_USER: "${COPY_POSTGRES_USER}"
      COPY_POSTGRES_PASSWORD: "${COPY_POSTGRES_PASSWORD}"
      FLYWAY_URL: "${FLYWAY_URL}"
      FLYWAY_USER: "${FLYWAY_USER}"
      FLYWAY_PASSWORD: "${FLYWAY_PASSWORD}"
      FLYWAY_PLACEHOLDERS_ORIGINAL_HOST_IP: "${FLYWAY_PLACEHOLDERS_ORIGINAL_HOST_IP}"
      FLYWAY_PLACEHOLDERS_ORIGINAL_DB: "${FLYWAY_PLACEHOLDERS_ORIGINAL_DB}"
      FLYWAY_PLACEHOLDERS_ORIGINAL_USER: "${FLYWAY_PLACEHOLDERS_ORIGINAL_USER}"
      FLYWAY_PLACEHOLDERS_ORIGINAL_PASSWORD: "${FLYWAY_PLACEHOLDERS_ORIGINAL_PASSWORD}"
      FLYWAY_PLACEHOLDERS_SUBSCRIPTION_NAME: "${FLYWAY_PLACEHOLDERS_SUBSCRIPTION_NAME}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
  gatekeeper:
    image: ${DOCKER_IMAGE_GATEKEEPER}:${DOCKER_TAG}
    restart: unless-stopped
    environment:
      PROXY_DISCOVERY_URL: "${KEYCLOAK_ENDPOINT}"
      PROXY_CLIENT_ID: "${KEYCLOAK_CLIENT_ID}"
      PROXY_CLIENT_SECRET: "${KEYCLOAK_CLIENT_SECRET}"
      PROXY_ENCRYPTION_KEY: "${KEYCLOAK_ENCRYPTION_KEY}"
  nginx:
    image: ${DOCKER_IMAGE_NGINX}:${DOCKER_TAG}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "${SERVER_PORT}:80"
