version: "3.4"

services:
  ontop:
    image: ${DOCKER_IMAGE_ONTOP}:${DOCKER_TAG}
    restart: unless-stopped
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/odh.ttl
      ONTOP_MAPPING_FILE: /opt/ontop/input/odh.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/odh.docker.properties
      ONTOP_PORTAL_FILE: /opt/ontop/input/odh.portal.toml
      ONTOP_PREDEFINED_CONFIG: /opt/ontop/input/predefined/predefined.json
      ONTOP_PREDEFINED_QUERIES: /opt/ontop/input/predefined/queries.toml
      ONTOP_CONTEXTS: /opt/ontop/input/predefined/contexts.json
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      COPY_POSTGRES_HOST: "${COPY_POSTGRES_HOST}"
      COPY_POSTGRES_DB: "${COPY_POSTGRES_DB}"
      COPY_POSTGRES_USER: "${COPY_POSTGRES_USER}"
      COPY_POSTGRES_PASSWORD: "${COPY_POSTGRES_PASSWORD}"
      FLYWAY_URL: "${FLYWAY_URL}"
      FLYWAY_USER: "${FLYWAY_USER}"
      FLYWAY_PASSWORD: "${FLYWAY_PASSWORD}"
      FLYWAY_PLACEHOLDERS_ORIGINAL_HOST_IP: "${FLYWAY_PLACEHOLDERS_ORIGINAL_HOST_IP}"
      FLYWAY_PLACEHOLDERS_ORIGINAL_DB: "${FLYWAY_PLACEHOLDERS_ORIGINAL_DB}"
      FLYWAY_PLACEHOLDERS_ORIGINAL_USER: "${FLYWAY_PLACEHOLDERS_ORIGINAL_USER}"
      FLYWAY_PLACEHOLDERS_ORIGINAL_PASSWORD: "${FLYWAY_PLACEHOLDERS_ORIGINAL_PASSWORD}"
      FLYWAY_PLACEHOLDERS_SUBSCRIPTION_NAME: "${FLYWAY_PLACEHOLDERS_SUBSCRIPTION_NAME}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
  oauth2:
    image: quay.io/oauth2-proxy/oauth2-proxy:v6.1.1
    restart: unless-stopped
    environment:
      OAUTH2_PROXY_PROVIDER: "keycloak"
      OAUTH2_PROXY_CLIENT_ID: "$KEYCLOAK_CLIENT_ID"
      OAUTH2_PROXY_CLIENT_SECRET: "$KEYCLOAK_CLIENT_SECRET"
      OAUTH2_PROXY_COOKIE_SECRET: "$OAUTH2_COOKIE_SECRET"
      OAUTH2_PROXY_LOGIN_URL: "$KEYCLOAK_REALM/protocol/openid-connect/auth"
      OAUTH2_PROXY_REDEEM_URL: "$KEYCLOAK_REALM/protocol/openid-connect/token"
      OAUTH2_PROXY_VALIDATE_URL: "$KEYCLOAK_REALM/protocol/openid-connect/userinfo"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_EMAIL_DOMAINS: "${OAUTH2_ALLOWED_EMAIL_DOMAINS}"
    # No `curl` command in image
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:4180/oauth2/ping/"]
    #   interval: 20s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 30s
  nginx:
    image: ${DOCKER_IMAGE_NGINX}:${DOCKER_TAG}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "${SERVER_PORT}:80"
